// apps/frontend/src/shared/components/TitleBar.vue
<template>
  <div class="title-bar">
    <h1 class="title">{{ title }}</h1>
    <div class="actions" v-if="actions && actions.length">
      <Button
        v-for="action in actions"
        :key="action.key"
        :color="action.color"
        :icon="action.icon"
        :size="action.size"
        :disabled="action.disabled"
        :loading="action.loading"
        @click="action.onClick"
        class="action-button"
      >
        {{ action.text }}
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue'

export interface TitleBarAction {
  key: string
  text: string
  icon?: string
  color?: string
  size?: string
  disabled?: boolean
  loading?: boolean
  onClick: () => void
}

defineProps<{
  title: string
  actions?: TitleBarAction[]
}>()
</script>

<style scoped>
@reference "@/app/assets/main.css";

.title-bar {
  @apply flex justify-between items-center mb-lg p-none;
}

.title {
  @apply m-none text-4xl font-bold;
}

.actions {
  @apply flex items-center gap-sm;
}

.action-button {
  @apply whitespace-nowrap;
}
</style>

// packages/ui-react/src/components/shared/TitleBar.tsx
import { Button } from '../ui/button'

export interface TitleBarAction {
  key: string
  text: string
  icon?: string
  variant?: 'default' | 'outline' | 'secondary' | 'ghost' | 'link' | 'destructive'
  size?: 'default' | 'sm' | 'lg' | 'icon'
  disabled?: boolean
  loading?: boolean
  onClick: () => void
}

interface TitleBarProps {
  title: string
  actions?: TitleBarAction[]
}

export function TitleBar({ title, actions }: TitleBarProps) {
  return (
    <div className="flex justify-between items-center mb-6">
      <h1 className="text-3xl font-bold">{title}</h1>
      {actions && actions.length > 0 && (
        <div className="flex items-center gap-2">
          {actions.map((action) => (
            <Button
              key={action.key}
              variant={action.variant || 'default'}
              size={action.size || 'lg'}
              disabled={action.disabled}
              onClick={action.onClick}
              className="whitespace-nowrap"
            >
              {action.icon && <span className="material-symbols-rounded">{action.icon}</span>}
              {action.text}
            </Button>
          ))}
        </div>
      )}
    </div>
  )
}
